text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512

gpt-3.5-turbo-0125:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo-0125"
        body:
            model: "gpt-3.5-turbo-0125"
            max_tokens: 512

gpt_rag_agent:
    import: "./gpt_rag_agent.yaml"
    parameters:
        name: "GptRAGAgent" # Ensure this matches the class name in your agent implementation
        body:
            model: "gpt_rag_agent"
            # max_tokens: 512
# python -m src.client.agent_test --config configs/agents/api_agents.yaml --agent gpt-3.5-turbo-0125
