import: definition.yaml

concurrency:
    task:
        dbbench-std: 5
        # os-std: 5
    agent:
        gpt_rag_agent: 10
        # gpt-3.5-turbo-0125: 5

assignments: # List[Assignment] | Assignment
    - agent: gpt_rag_agent
      task:
          - dbbench-std
          #   - os-std

output: "outputs/{TIMESTAMP}"
# import: definition.yaml

# concurrency:
#     task:
#         dbbench-std: 5
#         # os-std: 5
#     agent:
#         gpt_rag_agent: 1
#         # gpt-3.5-turbo-0125: 5

# assignments: # List[Assignment] | Assignment
#     - agent:
#           - module: "src.client.agents.GptRAGAgent"
#             parameters:
#                 name: "GptRAGAgent"
#                 body:
#                     model: "gpt-4"
#                     # max_tokens: 512
#       task:
#           - dbbench-std
#           #   - os-std

# output: "outputs/{TIMESTAMP}"
