import: definition.yaml

concurrency:
    task:
        avalon-dev-single: 3
    agent:
        gpt-3.5-turbo-0125: 3

assignments: # List[Assignment] | Assignment
    - agent: # "task": List[str] | str ,  "agent": List[str] | str
          - gpt-3.5-turbo-0125
      task:
          - avalon-dev-single

output: "outputs/{TIMESTAMP}"
