default:
    docker:
        command: umask 0; [ -f /root/.setup.sh ] && bash /root/.setup.sh;

import:
    - webshop.yaml
    - dbbench.yaml
    - mind2web.yaml
    - card_game.yaml
    - kg.yaml
    - os.yaml
    - ltp.yaml # Ensure this line is present
    - alfworld.yaml
    - avalon.yaml
